// <auto-generated />
// This snapshot is used by EF Core migrations tooling to detect model changes.
// It is regenerated automatically when you run: dotnet ef migrations add <Name>
// Do NOT edit manually — let EF Core manage this file.

using CleanArch.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable CS8981
namespace CleanArch.Infrastructure.Persistence.Migrations;

[DbContext(typeof(ApplicationDbContext))]
partial class ApplicationDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.6")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        // Tenants
        modelBuilder.Entity("CleanArch.Domain.Entities.Tenant", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedNever().HasColumnType("uniqueidentifier");
            b.Property<string>("BillingEmail").IsRequired().HasMaxLength(256).HasColumnType("nvarchar(256)");
            b.Property<string>("DefaultCurrency").IsRequired().IsFixedLength().HasMaxLength(3).HasColumnType("char(3)");
            b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
            b.Property<string>("Slug").IsRequired().HasMaxLength(63).HasColumnType("nvarchar(63)");
            b.Property<string>("Status").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)");
            b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
            b.Property<DateTime?>("UpdatedAt").IsConcurrencyToken().HasColumnType("datetime2");
            b.Property<bool>("IsDeleted").HasColumnType("bit");
            b.Property<DateTime?>("DeletedAt").HasColumnType("datetime2");
            b.Property<DateTime?>("TrialEndsAt").HasColumnType("datetime2");
            b.Property<DateTime?>("CancelledAt").HasColumnType("datetime2");
            b.HasKey("Id");
            b.HasIndex("Slug").IsUnique().HasDatabaseName("UX_Tenants_Slug");
            b.HasIndex("Status").HasDatabaseName("IX_Tenants_Status");
            b.ToTable("Tenants");
        });

        // Users
        modelBuilder.Entity("CleanArch.Domain.Entities.User", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedNever().HasColumnType("uniqueidentifier");
            b.Property<Guid>("TenantId").HasColumnType("uniqueidentifier");
            b.Property<string>("FirstName").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
            b.Property<string>("LastName").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
            b.Property<string>("Email").IsRequired().HasMaxLength(256).HasColumnType("nvarchar(256)");
            b.Property<string>("PasswordHash").IsRequired().IsFixedLength().HasMaxLength(60).HasColumnType("char(60)");
            b.Property<string>("Role").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)");
            b.Property<bool>("IsActive").HasColumnType("bit");
            b.Property<int>("FailedLoginAttempts").HasDefaultValue(0).HasColumnType("int");
            b.Property<DateTime?>("LockedUntil").HasColumnType("datetime2");
            b.Property<DateTime?>("LastLoginAt").HasColumnType("datetime2");
            b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
            b.Property<DateTime?>("UpdatedAt").IsConcurrencyToken().HasColumnType("datetime2");
            b.Property<bool>("IsDeleted").HasColumnType("bit");
            b.Property<DateTime?>("DeletedAt").HasColumnType("datetime2");
            b.HasKey("Id");
            b.HasIndex(new[] { "TenantId", "Email" }).IsUnique().HasDatabaseName("UX_Users_TenantId_Email");
            b.HasIndex("TenantId").HasDatabaseName("IX_Users_TenantId");
            b.ToTable("Users");
        });

        // Invoices
        modelBuilder.Entity("CleanArch.Domain.Entities.Invoice", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedNever().HasColumnType("uniqueidentifier");
            b.Property<Guid>("TenantId").HasColumnType("uniqueidentifier");
            b.Property<string>("InvoiceNumber").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
            b.Property<string>("CustomerName").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
            b.Property<string>("CustomerEmail").IsRequired().HasMaxLength(256).HasColumnType("nvarchar(256)");
            b.Property<string>("Status").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)");
            b.Property<string>("Currency").IsRequired().IsFixedLength().HasMaxLength(3).HasColumnType("char(3)");
            b.Property<decimal>("TaxRatePercentage").HasPrecision(5, 2).HasColumnType("decimal(5,2)");
            b.Property<decimal>("DiscountPercentage").HasPrecision(5, 2).HasColumnType("decimal(5,2)");
            b.Property<string>("LineItems").IsRequired().HasColumnType("nvarchar(max)");
            b.Property<string?>("Notes").HasMaxLength(2000).HasColumnType("nvarchar(2000)");
            b.Property<Guid>("CreatedByUserId").HasColumnType("uniqueidentifier");
            b.Property<DateTime?>("IssuedAt").HasColumnType("datetime2");
            b.Property<DateTime?>("DueDate").HasColumnType("datetime2");
            b.Property<DateTime?>("PaidAt").HasColumnType("datetime2");
            b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
            b.Property<DateTime?>("UpdatedAt").IsConcurrencyToken().HasColumnType("datetime2");
            b.Property<bool>("IsDeleted").HasColumnType("bit");
            b.Property<DateTime?>("DeletedAt").HasColumnType("datetime2");
            b.HasKey("Id");
            b.HasIndex(new[] { "TenantId", "InvoiceNumber" }).IsUnique().HasDatabaseName("UX_Invoices_TenantId_InvoiceNumber");
            b.HasIndex(new[] { "TenantId", "Status" }).HasDatabaseName("IX_Invoices_TenantId_Status");
            b.ToTable("Invoices");
        });

        // Payments
        modelBuilder.Entity("CleanArch.Domain.Entities.Payment", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedNever().HasColumnType("uniqueidentifier");
            b.Property<Guid>("TenantId").HasColumnType("uniqueidentifier");
            b.Property<Guid>("InvoiceId").HasColumnType("uniqueidentifier");
            b.Property<Guid?>("RefundedPaymentId").HasColumnType("uniqueidentifier");
            b.Property<string>("Status").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)");
            b.Property<string>("Type").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)");
            b.Property<string>("PaymentMethod").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
            b.Property<string?>("ExternalReference").HasMaxLength(200).HasColumnType("nvarchar(200)");
            b.Property<string?>("Notes").HasMaxLength(1000).HasColumnType("nvarchar(1000)");
            b.Property<string?>("FailureReason").HasMaxLength(500).HasColumnType("nvarchar(500)");
            b.Property<DateTime?>("CompletedAt").HasColumnType("datetime2");
            b.Property<Guid?>("InitiatedByUserId").HasColumnType("uniqueidentifier");
            b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
            b.Property<DateTime?>("UpdatedAt").HasColumnType("datetime2");
            b.Property<bool>("IsDeleted").HasColumnType("bit");
            b.Property<DateTime?>("DeletedAt").HasColumnType("datetime2");
            b.HasKey("Id");
            b.HasIndex(new[] { "TenantId", "InvoiceId", "CreatedAt" }).HasDatabaseName("IX_Payments_TenantId_InvoiceId_CreatedAt");
            b.ToTable("Payments");
        });

        // AuditLogs
        modelBuilder.Entity("CleanArch.Domain.Entities.AuditLog", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedNever().HasColumnType("uniqueidentifier");
            b.Property<Guid>("TenantId").HasColumnType("uniqueidentifier");
            b.Property<Guid?>("UserId").HasColumnType("uniqueidentifier");
            b.Property<string?>("UserDisplayName").HasMaxLength(200).HasColumnType("nvarchar(200)");
            b.Property<string>("Action").IsRequired().HasMaxLength(30).HasColumnType("nvarchar(30)");
            b.Property<string>("EntityType").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
            b.Property<Guid>("EntityId").HasColumnType("uniqueidentifier");
            b.Property<string>("Description").IsRequired().HasMaxLength(1000).HasColumnType("nvarchar(1000)");
            b.Property<string?>("StateBefore").HasColumnType("nvarchar(max)");
            b.Property<string?>("StateAfter").HasColumnType("nvarchar(max)");
            b.Property<string?>("IpAddress").HasMaxLength(45).HasColumnType("nvarchar(45)");
            b.Property<string?>("UserAgent").HasMaxLength(500).HasColumnType("nvarchar(500)");
            b.Property<string?>("CorrelationId").HasMaxLength(100).HasColumnType("nvarchar(100)");
            b.Property<string?>("Metadata").HasColumnType("nvarchar(max)");
            b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
            b.Property<bool>("IsDeleted").HasColumnType("bit");
            b.Property<DateTime?>("DeletedAt").HasColumnType("datetime2");
            b.HasKey("Id");
            b.HasIndex("TenantId").HasDatabaseName("IX_AuditLogs_TenantId");
            b.HasIndex(new[] { "TenantId", "EntityType", "EntityId" }).HasDatabaseName("IX_AuditLogs_Entity");
            b.HasIndex("CreatedAt").HasDatabaseName("IX_AuditLogs_CreatedAt");
            b.ToTable("AuditLogs");
        });
#pragma warning restore 612, 618
    }
}
