using ledgerflowApi.Domain.Common;
using ledgerflowApi.Domain.Events;
using ledgerflowApi.Domain.Exceptions;
using ledgerflowApi.Domain.ValueObjects;

namespace ledgerflowApi.Domain.Entities;

/// <summary>
/// The central financial document of the platform. Represents an itemised
/// bill from a tenant to one of their customers.
///
/// Aggregate rules:
/// - Invoice is its own aggregate root. LineItems are owned value objects —
///   they exist only as part of an invoice and are never shared.
/// - Payments are a separate aggregate that reference this Invoice by ID.
///   The Invoice tracks the total amount paid (PaidAmount) rather than
///   holding a collection of Payment entities to keep the aggregate boundary clean.
/// - Status transitions are strictly enforced by InvoiceStatus.CanTransitionTo().
///   Any attempt to jump to an invalid status throws InvalidStatusTransitionException.
///
/// Financial rules:
/// - An invoice must have at least one line item before it can be issued.
/// - Draft invoices can have lines added/removed freely.
/// - Once issued, the line items are frozen — no modifications allowed.
///   (Create a new invoice or void and re-issue for corrections.)
/// - Tax is calculated as a percentage of the subtotal and stored explicitly
///   so historical invoices are immune to tax rate changes.
/// - Payments are recorded against the invoice; when PaidAmount reaches
///   TotalAmount the status transitions to Paid automatically.
/// </summary>
public class Invoice : TenantEntity
{
    private readonly List<InvoiceLineItem> _lineItems = [];

    // ── Identity ─────────────────────────────────────────────────────────────

    /// <summary>
    /// Human-readable invoice number (e.g. "INV-2024-0042").
    /// Unique within the tenant. Generated by the application layer on creation
    /// using a tenant-scoped sequence so it is predictable and gap-free.
    /// </summary>
    public string InvoiceNumber { get; private set; } = string.Empty;

    // ── Customer ──────────────────────────────────────────────────────────────

    /// <summary>
    /// Free-form customer name as it should appear on the invoice.
    /// Stored as a snapshot — if the customer changes their name later,
    /// historical invoices are unaffected.
    /// </summary>
    public string CustomerName { get; private set; } = string.Empty;

    /// <summary>
    /// Customer's email address at the time the invoice was issued.
    /// Used to deliver the invoice; stored as a snapshot.
    /// </summary>
    public string CustomerEmail { get; private set; } = string.Empty;

    /// <summary>
    /// Optional billing address snapshot for the customer.
    /// Required on issued invoices for many jurisdictions (VAT compliance).
    /// </summary>
    public Address? BillingAddress { get; private set; }

    // ── Dates ─────────────────────────────────────────────────────────────────

    /// <summary>When the invoice was formally issued to the customer.</summary>
    public DateTime? IssuedAt { get; private set; }

    /// <summary>
    /// Payment due date. Set when the invoice is issued.
    /// The background job that marks invoices as Overdue checks this field.
    /// </summary>
    public DateTime? DueDate { get; private set; }

    /// <summary>When full payment was received and the invoice was closed.</summary>
    public DateTime? PaidAt { get; private set; }

    // ── Financials ────────────────────────────────────────────────────────────

    /// <summary>
    /// ISO 4217 currency for all monetary values on this invoice.
    /// Set at creation and never changes — mixing currencies on a single
    /// invoice is not supported (create separate invoices per currency).
    /// </summary>
    public string Currency { get; private set; } = string.Empty;

    /// <summary>
    /// Tax rate applied to the subtotal, stored as a percentage (e.g. 20.0 = 20%).
    /// Captured as a snapshot at issuance — changes to the tenant's tax rate
    /// do not retroactively alter issued invoices.
    /// </summary>
    public decimal TaxRatePercentage { get; private set; }

    /// <summary>
    /// Invoice-level discount percentage (0–100), applied after line-level discounts.
    /// e.g. a 5% loyalty discount on the whole invoice.
    /// </summary>
    public decimal DiscountPercentage { get; private set; }

    /// <summary>
    /// Total payments recorded against this invoice so far.
    /// Updated each time a Payment is applied via RecordPayment().
    /// </summary>
    public Money PaidAmount { get; private set; } = null!;

    // ── Status ────────────────────────────────────────────────────────────────

    public InvoiceStatus Status { get; private set; } = InvoiceStatus.Draft;

    /// <summary>Free-text notes printed on the invoice (e.g. payment instructions).</summary>
    public string? Notes { get; private set; }

    // ── Relationships ─────────────────────────────────────────────────────────

    /// <summary>The user within the tenant who created this invoice.</summary>
    public Guid CreatedByUserId { get; private set; }

    public User CreatedByUser { get; private set; } = null!;

    /// <summary>
    /// Value-object line items owned by this invoice aggregate.
    /// Stored as a JSON column or owned entity in EF Core — never a separate table
    /// with independent identity.
    /// </summary>
    public IReadOnlyCollection<InvoiceLineItem> LineItems => _lineItems.AsReadOnly();

    private Invoice() { } // EF Core

    // ── Factory ───────────────────────────────────────────────────────────────

    /// <summary>
    /// Creates a new draft invoice.
    /// All monetary values default to zero until line items are added.
    /// The invoice stays in Draft until explicitly issued.
    /// </summary>
    public static Invoice Create(
        Guid tenantId,
        Guid createdByUserId,
        string invoiceNumber,
        string customerName,
        string customerEmail,
        string currency,
        decimal taxRatePercentage = 0m,
        decimal discountPercentage = 0m,
        string? notes = null)
    {
        ValidateInvoiceNumber(invoiceNumber);
        ValidateCustomerName(customerName);
        ValidateEmail(customerEmail);
        ValidateCurrency(currency);
        ValidateTaxRate(taxRatePercentage);
        ValidateDiscount(discountPercentage);

        var invoice = new Invoice
        {
            TenantId = tenantId,
            CreatedByUserId = createdByUserId,
            InvoiceNumber = invoiceNumber.Trim(),
            CustomerName = customerName.Trim(),
            CustomerEmail = customerEmail.ToLowerInvariant().Trim(),
            Currency = currency.ToUpperInvariant(),
            TaxRatePercentage = taxRatePercentage,
            DiscountPercentage = discountPercentage,
            Notes = notes?.Trim(),
            Status = InvoiceStatus.Draft,
            PaidAmount = Money.Of(0m, currency.ToUpperInvariant())
        };

        return invoice;
    }

    // ── Line Item Management (Draft only) ─────────────────────────────────────

    /// <summary>
    /// Adds a line item to the invoice.
    /// Only allowed while the invoice is in Draft — once issued the document
    /// is frozen to preserve the audit trail and any customer agreements.
    /// </summary>
    public void AddLineItem(InvoiceLineItem lineItem)
    {
        if (!Status.IsDraft)
            throw new DomainException(
                $"Cannot modify line items on invoice '{InvoiceNumber}' — it is no longer a draft (current status: {Status}).");

        if (lineItem is null)
            throw new ArgumentNullException(nameof(lineItem));

        if (lineItem.UnitPrice.Currency != Currency)
            throw new DomainException(
                $"Line item currency ({lineItem.UnitPrice.Currency}) must match invoice currency ({Currency}).");

        _lineItems.Add(lineItem);
        SetUpdatedAt();
    }

    /// <summary>
    /// Removes a line item by its description and unit price.
    /// Only allowed on draft invoices.
    /// </summary>
    public void RemoveLineItem(InvoiceLineItem lineItem)
    {
        if (!Status.IsDraft)
            throw new DomainException(
                $"Cannot modify line items on invoice '{InvoiceNumber}' — status is {Status}.");

        var removed = _lineItems.Remove(lineItem);
        if (!removed)
            throw new DomainException("The specified line item was not found on this invoice.");

        SetUpdatedAt();
    }

    /// <summary>
    /// Replaces all line items at once.
    /// Useful during draft editing to avoid repeated add/remove calls.
    /// </summary>
    public void ReplaceLineItems(IEnumerable<InvoiceLineItem> lineItems)
    {
        if (!Status.IsDraft)
            throw new DomainException(
                $"Cannot replace line items on invoice '{InvoiceNumber}' — status is {Status}.");

        var items = lineItems?.ToList() ?? throw new ArgumentNullException(nameof(lineItems));
        if (items.Any(li => li.UnitPrice.Currency != Currency))
            throw new DomainException(
                $"All line item currencies must match the invoice currency ({Currency}).");

        _lineItems.Clear();
        _lineItems.AddRange(items);
        SetUpdatedAt();
    }

    // ── Status Transitions ────────────────────────────────────────────────────

    /// <summary>
    /// Issues the invoice, making it visible to the customer.
    ///
    /// Business rules enforced here:
    /// 1. Must be a draft — can't re-issue an already-issued invoice.
    /// 2. Must have at least one line item — a zero-line invoice has no value.
    /// 3. DueDate must be in the future — past-due invoices don't make sense at issuance.
    /// </summary>
    public void Issue(DateTime dueDate, Address? billingAddress = null)
    {
        GuardTransition(InvoiceStatus.Issued);

        if (!_lineItems.Any())
            throw new DomainException(
                $"Cannot issue invoice '{InvoiceNumber}' — it has no line items.");

        if (dueDate <= DateTime.UtcNow)
            throw new DomainException(
                $"Due date must be in the future. Provided: {dueDate:yyyy-MM-dd}.");

        IssuedAt = DateTime.UtcNow;
        DueDate = dueDate;
        BillingAddress = billingAddress;
        Status = InvoiceStatus.Issued;
        SetUpdatedAt();

        AddDomainEvent(new InvoiceIssuedEvent(Id, TenantId, InvoiceNumber, CustomerEmail));
    }

    /// <summary>
    /// Marks the invoice as overdue. Typically called by a scheduled job
    /// that runs nightly and checks for issued/partially-paid invoices past their DueDate.
    ///
    /// Business rule: can only go overdue from Issued or PartiallyPaid.
    /// A draft that was never sent cannot be "overdue" — it was never a commitment.
    /// </summary>
    public void MarkAsOverdue()
    {
        GuardTransition(InvoiceStatus.Overdue);

        if (!DueDate.HasValue || DueDate.Value >= DateTime.UtcNow)
            throw new DomainException(
                $"Cannot mark invoice '{InvoiceNumber}' as overdue — its due date has not passed.");

        Status = InvoiceStatus.Overdue;
        SetUpdatedAt();

        AddDomainEvent(new InvoiceOverdueEvent(Id, TenantId, InvoiceNumber, DueDate!.Value));
    }

    /// <summary>
    /// Voids the invoice, making it permanently invalid.
    ///
    /// Business rules:
    /// - A reason is required for audit trail purposes (legal requirement in many jurisdictions).
    /// - A fully paid invoice cannot be voided — issue a credit note instead.
    /// - Voiding is irreversible (terminal state).
    /// </summary>
    public void Void(string reason)
    {
        if (string.IsNullOrWhiteSpace(reason))
            throw new DomainException("A reason is required when voiding an invoice.");

        if (Status == InvoiceStatus.Paid)
            throw new DomainException(
                $"Cannot void a fully paid invoice ('{InvoiceNumber}'). " +
                "Issue a credit note or process a refund through the payment system.");

        GuardTransition(InvoiceStatus.Voided);

        Status = InvoiceStatus.Voided;
        Notes = string.IsNullOrWhiteSpace(Notes)
            ? $"VOIDED: {reason}"
            : $"{Notes} | VOIDED: {reason}";
        SetUpdatedAt();

        AddDomainEvent(new InvoiceVoidedEvent(Id, TenantId, InvoiceNumber, reason));
    }

    /// <summary>
    /// Records an incoming payment amount against this invoice.
    /// Called by the application layer when a Payment reaches Completed status.
    ///
    /// Business rules:
    /// 1. Payment cannot exceed the outstanding balance.
    /// 2. Payment currency must match the invoice currency (no FX on an invoice).
    /// 3. When the outstanding balance reaches zero, the invoice auto-transitions to Paid.
    /// 4. A partial payment transitions from Issued/Overdue to PartiallyPaid.
    /// 5. The payment must belong to the same tenant (enforced via TenantId guard).
    /// </summary>
    public void RecordPayment(Money amount, Guid paymentTenantId)
    {
        // Cross-tenant guard: a payment from a different tenant cannot be applied here.
        if (paymentTenantId != TenantId)
            throw new TenantMismatchException(
                $"applying payment to invoice '{InvoiceNumber}'");

        if (Status.IsVoided)
            throw new DomainException(
                $"Cannot apply a payment to voided invoice '{InvoiceNumber}'.");

        if (Status == InvoiceStatus.Paid)
            throw new DomainException(
                $"Invoice '{InvoiceNumber}' is already fully paid.");

        if (Status.IsDraft)
            throw new DomainException(
                $"Cannot apply a payment to draft invoice '{InvoiceNumber}'. Issue the invoice first.");

        if (amount.Currency != Currency)
            throw new DomainException(
                $"Payment currency ({amount.Currency}) does not match invoice currency ({Currency}).");

        var outstanding = OutstandingAmount;
        if (amount.IsGreaterThan(outstanding))
            throw new DomainException(
                $"Payment of {amount} exceeds the outstanding balance of {outstanding} on invoice '{InvoiceNumber}'.");

        PaidAmount = PaidAmount.Add(amount);
        SetUpdatedAt();

        // Auto-transition based on new paid amount
        if (PaidAmount == TotalAmount)
        {
            Status = InvoiceStatus.Paid;
            PaidAt = DateTime.UtcNow;
            AddDomainEvent(new InvoicePaidEvent(Id, TenantId, InvoiceNumber));
        }
        else if (Status == InvoiceStatus.Issued || Status == InvoiceStatus.Overdue)
        {
            Status = InvoiceStatus.PartiallyPaid;
        }
    }

    /// <summary>
    /// Reverses a previously applied payment (e.g. on chargeback or refund processing).
    /// The invoice status is recalculated from the new PaidAmount.
    /// </summary>
    public void ReversePayment(Money amount, Guid paymentTenantId)
    {
        if (paymentTenantId != TenantId)
            throw new TenantMismatchException($"reversing payment on invoice '{InvoiceNumber}'");

        if (amount.Currency != Currency)
            throw new DomainException(
                $"Reversal currency ({amount.Currency}) does not match invoice currency ({Currency}).");

        if (amount.IsGreaterThan(PaidAmount))
            throw new DomainException(
                $"Cannot reverse {amount} — only {PaidAmount} has been paid on invoice '{InvoiceNumber}'.");

        PaidAmount = PaidAmount.Subtract(amount);
        PaidAt = null;

        // Recalculate status: if past due date go back to Overdue, else Issued or PartiallyPaid
        var isPastDue = DueDate.HasValue && DueDate.Value < DateTime.UtcNow;

        Status = PaidAmount.IsZero
            ? (isPastDue ? InvoiceStatus.Overdue : InvoiceStatus.Issued)
            : (isPastDue ? InvoiceStatus.Overdue : InvoiceStatus.PartiallyPaid);

        SetUpdatedAt();
    }

    // ── Computed Financials ───────────────────────────────────────────────────

    /// <summary>
    /// Sum of all line net amounts (after line-level discounts) before invoice discount and tax.
    /// </summary>
    public Money Subtotal => _lineItems.Any()
        ? _lineItems.Aggregate(
            Money.Of(0m, Currency),
            (acc, li) => acc.Add(li.NetAmount))
        : Money.Of(0m, Currency);

    /// <summary>The monetary value of the invoice-level discount.</summary>
    public Money InvoiceDiscountAmount => Subtotal.Multiply(DiscountPercentage / 100m);

    /// <summary>Subtotal after the invoice-level discount is applied.</summary>
    public Money DiscountedSubtotal => Subtotal.ApplyDiscount(DiscountPercentage);

    /// <summary>
    /// Tax amount. Calculated from the discounted subtotal so discounts
    /// reduce the taxable base — the common behaviour in most tax jurisdictions.
    /// </summary>
    public Money TaxAmount => DiscountedSubtotal.Multiply(TaxRatePercentage / 100m);

    /// <summary>Grand total: discounted subtotal + tax. This is what the customer pays.</summary>
    public Money TotalAmount => DiscountedSubtotal.Add(TaxAmount);

    /// <summary>How much is still owed on this invoice.</summary>
    public Money OutstandingAmount => TotalAmount.Subtract(PaidAmount);

    /// <summary>True when the invoice has been issued and payment is expected.</summary>
    public bool IsPayable =>
        Status is not { } s || (s != InvoiceStatus.Draft && s != InvoiceStatus.Paid && s != InvoiceStatus.Voided);

    // ── Helpers ───────────────────────────────────────────────────────────────

    /// <summary>
    /// Central guard for all status transitions.
    /// Throws a descriptive exception when the transition is invalid so
    /// callers get a clear message about what went wrong and why.
    /// </summary>
    private void GuardTransition(InvoiceStatus target)
    {
        if (!Status.CanTransitionTo(target))
            throw new InvalidStatusTransitionException(
                nameof(Invoice), Status.Value, target.Value);
    }

    private static void ValidateInvoiceNumber(string number)
    {
        if (string.IsNullOrWhiteSpace(number))
            throw new DomainException("Invoice number is required.");
        if (number.Length > 50)
            throw new DomainException("Invoice number cannot exceed 50 characters.");
    }

    private static void ValidateCustomerName(string name)
    {
        if (string.IsNullOrWhiteSpace(name))
            throw new DomainException("Customer name is required.");
        if (name.Length > 200)
            throw new DomainException("Customer name cannot exceed 200 characters.");
    }

    private static void ValidateEmail(string email)
    {
        if (string.IsNullOrWhiteSpace(email))
            throw new DomainException("Customer email is required.");
        if (!email.Contains('@'))
            throw new DomainException("Customer email must be a valid email address.");
    }

    private static void ValidateCurrency(string currency)
    {
        if (string.IsNullOrWhiteSpace(currency) || currency.Length != 3)
            throw new DomainException("Currency must be a 3-character ISO 4217 code.");
    }

    private static void ValidateTaxRate(decimal rate)
    {
        if (rate < 0 || rate > 100)
            throw new DomainException("Tax rate must be between 0 and 100.");
    }

    private static void ValidateDiscount(decimal discount)
    {
        if (discount < 0 || discount > 100)
            throw new DomainException("Invoice discount must be between 0 and 100.");
    }
}
